---
openapi: 3.0.1
info:
  title: API documentation for users
  version: v1
paths:
  "/api/v1/products/{id}":
    get:
      summary: Retrieve a product
      tags:
      - Products
      description: Get the product information.
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Product found
          examples:
            application/json:
              id: 1
              price: '99.84999999999999'
              title: Incredible Leather Keyboard
              user_id: 1
        '401':
          description: Unauthenticated
          examples:
            application/json:
              description: Cannot perform this action over product due to unauthenticated
                request
              error_code: 4204
        '403':
          description: Unauthorized
          examples:
            application/json:
              description: Cannot perform this action over product due to unauthorized
                request
              details: not allowed to show? this Product
              error_code: 4205
        '404':
          description: Product not found
          examples:
            application/json:
              description: Product not found
              details: Couldn't find Product with 'id'=0
              error_code: 4202
        '500':
          description: Internal server error
  "/api/v1/products":
    get:
      summary: Retrieve the list of products
      tags:
      - Products
      description: Get the list of products with their information.
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: List returned
          examples:
            application/json:
            - id: 6
              price: '10.21'
              title: Intelligent Wool Shirt
              user_id: 7
        '401':
          description: Unauthenticated
          examples:
            application/json:
              description: Cannot perform this action over product due to unauthenticated
                request
              error_code: 4204
        '403':
          description: Unauthorized
          examples:
            application/json:
              description: Cannot perform this action over product due to unauthorized
                request
              details: not allowed to  this NilClass
              error_code: 4205
        '500':
          description: Internal server error
    post:
      summary: Create a product
      tags:
      - Products
      description: Create a product.
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: Product created
          examples:
            application/json:
              id: 9
              price: '92.98999999999999'
              title: Mediocre Linen Plate
              user_id: 10
        '401':
          description: Unauthenticated
          examples:
            application/json:
              description: Cannot perform this action over product due to unauthenticated
                request
              error_code: 4204
        '403':
          description: Unauthorized
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: object
                  properties:
                    title:
                      type: string
                    price:
                      type: string
                    published:
                      type: string
                  required:
                  - title
                  - price
                required:
                - product
  "/api/v1/tokens":
    post:
      summary: create
      tags:
      - Token
      description: Get a Json Web Token.
      parameters: []
      responses:
        '200':
          description: User created
          examples:
            application/json:
              token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMywiZXhwIjoxNjM4MzAwMjIzfQ.Kr7MppKvKZWPNCvvRLm027YtdLAHcjIpHX5mfqO8rOo
              email: quentin_funk@haag-stokes.com
        '401':
          description: User not found
          examples:
            application/json:
              description: Cannot authenticate user due to invalid credentials
              error_code: 4003
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
                required:
                - user
  "/api/v1/users/{id}":
    get:
      summary: Retrieve a user
      tags:
      - Users
      description: Get the user information.
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User found
          examples:
            application/json:
              email: sherry.koepp@kessler-murazik.io
              id: 16
        '404':
          description: User not found
          examples:
            application/json:
              description: User not found
              details: Couldn't find User with 'id'=0
              error_code: 4100
        '500':
          description: Internal server error
    put:
      summary: Update a user
      tags:
      - Users
      description: Update a user.
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User updated
          examples:
            application/json:
              email: melida@vandervort.info
              id: 23
        '401':
          description: User can not be deleted or updated due to unauthorized
          examples:
            application/json:
              description: Cannot perform this action over user due to unauthenticated
                request
              error_code: 4107
        '422':
          description: Cannot update profile due to invalid paramater
          examples:
            application/json:
              description: Cannot update user profile to invalid paramater
              details:
              - is not an email
              error_code: 4105
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
                required:
                - user
    delete:
      summary: Delete a user
      tags:
      - Users
      description: Delete a user.
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: User deleted
        '401':
          description: User can not be deleted or updated due to unauthorized
        '500':
          description: Internal server error
  "/api/v1/users":
    post:
      summary: Create a user
      tags:
      - Users
      description: Create a user.
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: User created
          examples:
            application/json:
              email: brunilda@schmitt.name
              id: 20
        '422':
          description: Cannot create profile due to invalid paramater
          examples:
            application/json:
              description: Cannot create user due to invalid parameters
              details:
              - is not an email
              error_code: 4104
        '500':
          description: Internal server error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
                required:
                - user
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
components:
  securitySchemes:
    BearerAuth:
      type: apiKey
      name: Authorization
      in: header
