# frozen_string_literal: true

# Generic errors
5000:
  :http_status: 500
  :error_code: 5000
  :description: 'Internal server error'
4001:
  :http_status: 400
  :error_code: 4001
  :description: 'Missing Parameter'
4002:
  :http_status: 401
  :error_code: 4002
  :description: 'Cannot perform this action due to unauthenticated request'
4003:
  :http_status: 401
  :error_code: 4003
  :description: 'Cannot authenticate user due to invalid credentials'

# User errors
4100:
  :http_status: 404
  :error_code: 4100
  :description: 'User not found'
4102:
  :http_status: 404
  :error_code: 4102
  :description: 'User can not be deleted or updated due to user not found'
4103:
  :http_status: 403
  :error_code: 4103
  :description: 'User cannot perform this action due to unauthorized request'
4104:
  :http_status: 422
  :error_code: 4104
  :description: 'Cannot create user due to invalid parameters'
4105:
  :http_status: 422
  :error_code: 4105
  :description: 'Cannot update user profile to invalid paramater'
4106:
  :http_status: 422
  :error_code: 4106
  :description: 'The email is already in use'
4107:
  :http_status: 401
  :error_code: 4107
  :description: 'Cannot perform this action over user due to unauthenticated request'

# Product errors  
4200:
  :http_status: 400
  :error_code: 4200
  :description: 'Product can not be created due to bad request'
4201:
  :http_status: 400
  :error_code: 4201
  :description: 'Product can not be updated due to bad request'
4202:
  :http_status: 404
  :error_code: 4202
  :description: 'Product not found'
4203:
  :http_status: 403
  :error_code: 4203
  :description: 'Product can not be updated due to unauthorized request'
4204:
  :http_status: 401
  :error_code: 4204
  :description: 'Cannot perform this action over product due to unauthenticated request'
4205:
  :http_status: 403
  :error_code: 4205
  :description: 'Cannot perform this action over product due to unauthorized request'
4206:
  :http_status: 403
  :error_code: 4206
  :description: 'Product can not be deleted due to unauthorized request'
4207:
  :http_status: 403
  :error_code: 4207
  :description: 'Product cannot be transferred due to unauthorized request'
4208:
  :http_status: 422
  :error_code: 4208
  :description: 'Product cannot be transferred due to a problem with the target user'
4209:
  :http_status: 422
  :error_code: 4209
  :description: 'Product cannot be transferred due to the target user cannot be found'