# frozen_string_literal: true

5000:
  :http_status: 500
  :error_code: 5000
  :description: 'Internal server error'
4000:
  :http_status: 404
  :error_code: 4000
  :description: 'Not found'
4001:
  :http_status: 400
  :error_code: 4001
  :description: 'Missing Parameter'
4002:
  :http_status: 404
  :error_code: 4002
  :description: 'User can not be deleted or updated due to user not found'
4003:
  :http_status: 401
  :error_code: 4003
  :description: 'User can not be deleted or updated due to unauthorized'
4004:
  :http_status: 422
  :error_code: 4004
  :description: 'Cannot create profile due to invalid parameter'
4005:
  :http_status: 422
  :error_code: 4005
  :description: 'Cannot update profile due to invalid paramater'
4006:
  :http_status: 400
  :error_code: 4006
  :description: 'Invalid parameter in product'
4007:
  :http_status: 404
  :error_code: 4007
  :description: 'Product not found'
4008:
  :http_status: 401
  :error_code: 4008
  :description: 'Product can not be deleted or updated due to being unauthorized'
