# frozen_string_literal: true

5000:
  :http_status: 500
  :error_code: 5000
  :description: 'Internal server error'
4000:
  :http_status: 404
  :error_code: 4000
  :description: 'Not found'
4001:
  :http_status: 400
  :error_code: 4001
  :description: 'Missing Parameter'
4010:
  :http_status: 404
  :error_code: 4010
  :description: 'User can not be deleted or updated due to user not found'
4011:
  :http_status: 401
  :error_code: 4011
  :description: 'User can not be deleted or updated due to unauthorized'
4022:
  :http_status: 422
  :error_code: 4022
  :description: 'Cannot create profile due to invalid paramater'
4023:
  :http_status: 422
  :error_code: 4023
  :description: 'Cannot update profile due to invalid paramater'
  :description: 'Invalid Parameter'
4030:
  :http_status: 400
  :error_code: 4030
  :description: 'Invalid parameter in product'
